[package]
name = "cs50-rust"
version = "0.1.0"
authors = ["Felix Andreas <felix.andreas95@googlemail.com>"]
edition = "2018"

[[bin]]
name = "recover"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
