[package]
name = "learn-ndarray"
version = "0.1.0"
authors = ["Felix Andreas"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = { version = "0.15.2", features = [] }
